---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - calculator.sample-k8s-ctrl.github.com
  resources:
  - calculators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calculator.sample-k8s-ctrl.github.com
  resources:
  - calculators/finalizers
  verbs:
  - update
- apiGroups:
  - calculator.sample-k8s-ctrl.github.com
  resources:
  - calculators/status
  verbs:
  - get
  - patch
  - update
