apiVersion: test1.samples-k8s-ctrl.github.com/v1alpha1
kind: SimpleDeployment
metadata:
  name: simpledeployment-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  mymetadata: 
    labels: 
      app: nginx
        